### ISSUE TITLE
Error when using lz4 version 0.18.1

### ISSUE THREAD

**Issue by tzulberti-jampp** [jampp/sharedbuffers#24]
When using lz4 0.18.1 the following error take place:

```
  File "multihashmap.py", line 6, in <module>
    import sharedbuffers
  File "sharedbuffers/__init__.py", line 4, in <module>
    from .mapped_struct import *
  File "sharedbuffers/mapped_struct.py", line 301, in init sharedbuffers.mapped_struct (sharedbuffers/mapped_struct.c:90845)
    lz4_decompress = cython.declare(object, lz4.decompress)
AttributeError: 'module' object has no attribute 'decompress'
```

Based on the documentation it should use the `frame` module to access that functions: http://python-lz4.readthedocs.io/en/stable/lz4.frame.html

**Comment by klaussfreire** [comment]
> Based on the documentation it should use the `frame` module to access that functions: http://python-lz4.readthedocs.io/en/stable/lz4.frame.html

There, it says:

> This sub-package is in beta testing.

What a great project huh? Deprecating a stable API in favor of a beta. Wow.
